---
- name: create kibana.repo
  template:
    src: "{{ path_home }}/roles/kibana/templates/kibana.repo.j2"
    dest: "/etc/yum.repos.d/kibana.repo"
    owner: root
    group: root
    mode: "0644"

- name: install kibana
  yum:
    name: kibana
    state: present

- name: edit url kibana.yml
  template:
    src: "{{ path_home }}/roles/kibana/templates/kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"
    owner: root
    group: root
    mode: "0644"
    
- name: start kibana
  service:
    name: kibana
    state: started
    enabled: yes

