---
- name: create elasticsearch.repo 
  template: 
    src: "{{ path_home }}/roles/elasticsearch/templates/elasticsearch.repo.j2"
    dest: "/etc/yum.repos.d/elasticsearch.repo"
    owner: root 
    group: root 
    mode: "0644"

- name: install elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: edit elasticsearch.yml
  template:
    src: "{{ path_home }}/roles/elasticsearch/templates/elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: elasticsearch
    mode: "0660"
    
- name: start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: open port firewalld for elasticsearch
  firewalld:
    port: 9200/tcp
    permanent: yes
    state: enabled
    
- name: restart firewalld
  service: name=firewalld state=restarted
